version: 0.5.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
skip_branch_with_pr: false
test: off

os: Visual Studio 2017

environment:
  CI: true

nuget:
  account_feed: true
  project_feed: true
#   disable_publish_on_pr: true

install:
  - ps: Install-Product node LTS
  - ps: choco install dotnetcore-sdk --no-progress --confirm --version 2.1.403
  - node --version
  - npm --version
  - dotnet --version

build_script:
- cmd: >-
    npm build:ci
artifacts:
  - path: 'artifacts\*.nupkg'

deploy:
- provider: NuGet
  server:
  api_key:
    secure: 2IahWGz4z1Hjob2zdT7O++4yoa8PpsgJWiJozzXWgfzMUAhwDp1XXHQ+R46M10Bq
  skip_symbols: false
  symbol_server:
  on:
    branch:
      - master
